### ISSUE TITLE
Shimar secret is created using only alphanumeric values

### ISSUE THREAD

**Issue by free-Runner** [PolyPasswordHasher/PolyPasswordHasher-Django#4]
The secret is [generated](https://github.com/PolyPasswordHasher/PolyPasswordHasher-Django/blob/master/django_pph/management/commands/initialize_pph_context.py#L37) using get_random_string from [django.utils.crypto](https://github.com/django/django/blob/master/django/utils/crypto.py#L54). Since no second parameter is provided, the default character set (A-Z,a-z,0-9) is used instead of the set of all byte values (0x00-0xff). 

Since the function description mentions "28 bytes of random data", I'm assuming the intent is to use the latter set of values and not the former.

**Comment by SantiagoTorres** [comment]
Thanks for letting us know!

Yes, using the whole byte-space is what we intended to do. I'll update everything accordingly.
