### ISSUE TITLE
[Polypasswordhasher-django]Update location tag under share_cache field in settings.py 

### ISSUE THREAD

**Issue by asm582** [PolyPasswordHasher/PolyPasswordHasher-Django#6]
Currently:
 'share_cache': {
            'BACKEND': 'django.core.cache.backends.db.DatabaseCache',
            'LOCATION': 'share_table',
    },

Change to :

 'share_cache': {
            'BACKEND': 'django.core.cache.backends.db.DatabaseCache',
            'LOCATION': 'share_cache',
    },

**Comment by SantiagoTorres** [comment]
Just updated the wiki, 
Thanks!
