### ISSUE TITLE
Minor issue with migrate_user.py

### ISSUE THREAD

**Issue by free-Runner** [PolyPasswordHasher/PolyPasswordHasher-Django#7]
This command won't function correctly as the algorithm ('pkbdf2_sha256') listed in  SUPPORTED_HASHES is misspelled. Should be 'pbkdf2_sha256'.

**Comment by SantiagoTorres** [comment]
Wow, I'm actually surprised. I tested this command not too long ago. 
We also had someone else use it... wonder how it happened.

I'll patch this right away. Thanks!

**Comment by SantiagoTorres** [comment]
This is fixed in #8
